server:
  port: 2002

spring:
  ##服务名
  application:
    name: seata-storage-service

  ##数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.100:3306/seata_storage?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

  ##注册中心&seata
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848

  zipkin:
    base-url: http://192.168.1.100:9411
  sleuth:
    sampler:
      probability: 1

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.1.100:8848
      group: DEFAULT_GROUP
      cluster: default
      namespace:
  service:
    vgroup-mapping:
      my_test_tx_group: default

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.tchi.springcloud.entity

feign:
  hystrix:
    enabled: false
