server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.100:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  #所有entity别名类所在包
  type-aliases-package: com.tchi.springcloud.entity
